In [1]:
import time
import pandas as  pd

filepath = 'G:\\내 드라이브\\DataSet\\_파킷 파일\\'
filename = '연도별 자치구별 출퇴근 이동인구 2020-2024.parquet'
start_time = time.time()
df = pd.read_parquet(filepath + filename)
print("read_parquet time :", time.time() - start_time)
df.head(5)

read_parquet time : 0.8561944961547852

     연도 출퇴근  자치구         이동인구
0  2020  출근  강남구  42087137.37
1  2020  출근  강동구   8690787.78
2  2020  출근  강북구   4228968.36
3  2020  출근  강서구  12350053.62
4  2020  출근  관악구   6552387.52

In [3]:
df

       연도 출퇴근  자치구         이동인구
0    2020  출근  강남구  42087137.37
1    2020  출근  강동구   8690787.78
2    2020  출근  강북구   4228968.36
3    2020  출근  강서구  12350053.62
4    2020  출근  관악구   6552387.52
..    ...  ..  ...          ...
245  2024  퇴근  용산구   8638774.97
246  2024  퇴근  은평구  17598681.48
247  2024  퇴근  종로구   6011493.14
248  2024  퇴근   중구   4834166.40
249  2024  퇴근  중랑구  13623038.79

[250 rows x 4 columns]

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      250 non-null    object
 1   출퇴근     250 non-null    object
 2   자치구     250 non-null    object
 3   이동인구    250 non-null    float64
dtypes: float64(1), object(3)
memory usage: 7.9+ KB

In [37]:
df_year = df[df['연도'] == '2024']
df_year

       연도 출퇴근   자치구         이동인구
200  2024  출근   강남구  44904151.17
201  2024  출근   강동구  13038618.21
202  2024  출근   강북구   5803004.16
203  2024  출근   강서구  16328231.44
204  2024  출근   관악구   9282364.87
205  2024  출근   광진구   8434285.94
206  2024  출근   구로구  12075879.50
207  2024  출근   금천구  10620282.28
208  2024  출근   노원구  10627911.14
209  2024  출근   도봉구   5441955.65
210  2024  출근  동대문구  10208506.04
211  2024  출근   동작구   8000823.90
212  2024  출근   마포구  14644735.04
213  2024  출근  서대문구  11818650.13
214  2024  출근   서초구  27691565.02
215  2024  출근   성동구  12122873.31
216  2024  출근   성북구   9039584.48
217  2024  출근   송파구  23114998.50
218  2024  출근   양천구   7559775.59
219  2024  출근  영등포구  27080281.21
220  2024  출근   용산구  10252816.61
221  2024  출근   은평구   7996820.42
222  2024  출근   종로구  18857049.82
223  2024  출근    중구  26897204.03
224  2024  출근   중랑구   7404466.64
225  2024  퇴근   강남구  21597789.01
226  2024  퇴근   강동구  20950420.71
227  2024  퇴근   강북구  10508866.58
228  2024  퇴근   강서구  19318424.40
229  2024  퇴근   관악구  16472059.56
230  2024  퇴근   광진구  13623811.42
231  2024  퇴근   구로구  15256755.58
232  2024  퇴근   금천구   7458451.18
233  2024  퇴근   노원구  18504245.70
234  2024  퇴근   도봉구  10518450.35
235  2024  퇴근  동대문구  12609141.46
236  2024  퇴근   동작구  14423193.77
237  2024  퇴근   마포구  14261434.97
238  2024  퇴근  서대문구  12101423.98
239  2024  퇴근   서초구  16100046.09
240  2024  퇴근   성동구  11957803.98
241  2024  퇴근   성북구  16091017.02
242  2024  퇴근   송파구  26777253.97
243  2024  퇴근   양천구  13846689.39
244  2024  퇴근  영등포구  15722979.60
245  2024  퇴근   용산구   8638774.97
246  2024  퇴근   은평구  17598681.48
247  2024  퇴근   종로구   6011493.14
248  2024  퇴근    중구   4834166.40
249  2024  퇴근   중랑구  13623038.79

In [39]:
import pandas as pd
import numpy as np
import json

import folium

In [41]:
# 나의 루트 경로 설정
path_dateset = 'G:/내 드라이브/DataSet/'
save_name = '(folium)지도테마_자치구구분_출퇴근이동인구'

## 데이터 불러오기

### 자전거 대여소 정보

In [43]:
rental = pd.read_parquet(path_dateset + '_파킷 파일\\서울시 공공자전거 대여소 정보\\공공자전거 대여소 정보_통합본_최종.parquet')
rental.head()

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,데이터등록월,대여소ID,거치대수
0,06173,서울자동차운전전문학원,강서구,강서구 남부순환로 216,37.546135,126.821060,2024-03-18,NaN,10.0,QR,2024-06,ST-3284,NaN
1,02902,공릉풍림아파트 108동,노원구,서울특별시 노원구 섬밭로 139 공릉풍림아파트,37.628620,127.066910,2020-03-24,NaN,12.0,QR,2024-06,ST-2068,NaN
2,02912,대진고등학교,노원구,서울특별시 노원구 한글비석로 97,37.638157,127.073265,2020-03-23,NaN,20.0,QR,2024-06,ST-2078,NaN
3,02911,상계역중앙시장,노원구,서울특별시 노원구 한글비석로 389-2 가로판매대,37.658871,127.071915,2020-03-23,NaN,7.0,QR,2024-06,ST-2077,NaN
4,02910,도깨비시장,노원구,서울특별시 노원구 동일로 1028 한의학명가,37.621864,127.074051,2020-03-25,NaN,10.0,QR,2024-06,None,NaN

### 자치구 정보

In [45]:
geo_path = path_dateset + 'seoul_municipalities_geo_simple.json'
# geo_str = json.load(open(geo_path, encoding='cp949'))
# encoding을 UTF-8로 지정
with open(geo_path, 'rt', encoding='utf-8') as f:
    geo_str2 = json.load(f)
# # ============================

In [47]:
rental[rental['위도'].isnull()]

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,데이터등록월,대여소ID,거치대수
2918,04205,디지털미디어씨티역2번출구,마포구,마포구 상암동 1171-1,NaN,NaN,2020-12-02,NaN,10.0,QR,2021-01,None,NaN

### 지하철역통합_20241031.parquet

In [49]:
filename = '_최종 병합 파일\\서울교통공사 역주소 및 전화번호\\지하철역통합_20241031.parquet'
df_train_station = pd.read_parquet(path_dateset + filename)
df_train_station.head()

,연번,역번호,호선,역명,역전화번호,도로명주소,지번주소,station_code,seoulmetro_code,external_code,station_name(kor),lat,lng
0,NaN,None,NaN,<NA>,<NA>,<NA>,<NA>,651.0,4703,943,419민주묘지,37.648235,127.008614
1,NaN,None,NaN,<NA>,<NA>,<NA>,<NA>,335.0,1907,109,가능,37.748577,127.044213
2,92.0,340,3.0,가락시장,02-6110-3501,서울특별시 송파구 송파대로 지하257(가락동),서울특별시 송파구 가락동 184-23 가락시장역(3호선),78.0,340,350,가락시장,37.492522,127.118234
3,NaN,None,NaN,<NA>,<NA>,<NA>,<NA>,230.0,1702,P142,가산디지털단지,37.481072,126.882343
4,NaN,None,NaN,<NA>,<NA>,<NA>,<NA>,580.0,4107,907,가양,37.561391,126.854456

In [73]:
move = df_year.groupby('자치구')['이동인구'].sum().reset_index()
move

     자치구         이동인구
0    강남구  66501940.18
1    강동구  33989038.92
2    강북구  16311870.74
3    강서구  35646655.84
4    관악구  25754424.43
5    광진구  22058097.36
6    구로구  27332635.08
7    금천구  18078733.46
8    노원구  29132156.84
9    도봉구  15960406.00
10  동대문구  22817647.50
11   동작구  22424017.67
12   마포구  28906170.01
13  서대문구  23920074.11
14   서초구  43791611.11
15   성동구  24080677.29
16   성북구  25130601.50
17   송파구  49892252.47
18   양천구  21406464.98
19  영등포구  42803260.81
20   용산구  18891591.58
21   은평구  25595501.90
22   종로구  24868542.96
23    중구  31731370.43
24   중랑구  21027505.43

In [86]:
move.sort_values(ascending = False, inplace = True)

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [27]:
import ast

text = '"\ub3c4\ubd09\uad6c"'
decoded_text = ast.literal_eval(text)
print(decoded_text)

도봉구

In [92]:
# 지도 생성
center = [37.541, 126.986]
bike_map = folium.Map(location=center, zoom_start=13, tiles='openstreetmap', name='OpenStreetMap')

# 자치구 구분 JSON 파일 로드
geo_str2 = json.load(open('G:\\내 드라이브\\DataSet\\seoul_municipalities_geo_simple.json', encoding='utf-8'))

# Choropleth 생성 (columns 매개변수 추가)
choropleth = folium.Choropleth(
    geo_data=geo_str2,
    data=move,
    columns=['자치구', '이동인구'],  # '자치구'를 키로 하고, '이동인구' 값을 사용할 열로 지정
    key_on='feature.properties.SIG_KOR_NM',
    fill_color='Blues',
    fill_opacity=0.3
)

# GeoJsonPopup 추가
folium.GeoJsonPopup(fields=['SIG_KOR_NM'], aliases=['지역:'], style='font-weight: bold;').add_to(choropleth.geojson)

# Choropleth를 지도에 추가
choropleth.add_to(bike_map)

# 타일 레이어 및 레이어 컨트롤 추가
folium.TileLayer('cartodbpositron', name='CartoDB Positron').add_to(bike_map)
folium.TileLayer('cartodbdark_matter', name='CartoDB Dark Matter').add_to(bike_map)
folium.LayerControl().add_to(bike_map)

# 지도 저장
save_name = "bike_map"
bike_map.save(save_name + ".html")

# 웹 브라우저에서 지도 열기
import webbrowser
webbrowser.open(save_name + ".html")

True